# Generated by Django 3.2.4 on 2023-12-22 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dp', models.ImageField(upload_to='resume/images/dps/')),
                ('objective', models.TextField()),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('city_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resume.city')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer', models.TextField(default=None)),
                ('liked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='skillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluency', models.CharField(choices=[('BR', 'Beginner'), ('IN', 'Intermediate'), ('EX', 'Expert')], max_length=2)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.skill')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='state_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resume.state'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='experienceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.DateField()),
                ('end_year', models.DateField(blank=True, null=True)),
                ('company', models.CharField(default=None, max_length=100)),
                ('experience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.experience')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile')),
            ],
        ),
        migrations.CreateModel(
            name='courseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('marks', models.FloatField(max_length=100)),
                ('total_marks', models.FloatField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.course')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.state'),
        ),
        migrations.CreateModel(
            name='certificateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('year', models.CharField(max_length=4)),
                ('certificate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.certification')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile')),
            ],
        ),
        migrations.CreateModel(
            name='awardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('award_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.award')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile')),
            ],
        ),
    ]
