# Generated by Django 3.2.4 on 2023-12-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprofile',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='experienceprofile',
            options={'ordering': ['-end_year']},
        ),
    ]
