# Generated by Django 3.2.4 on 2023-12-26 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_experienceprofile_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceprofile',
            name='end_year',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 26, 19, 43, 57, 747076)),
        ),
    ]
