# Generated by Django 3.2.4 on 2024-01-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_experienceprofile_end_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='liked',
        ),
    ]
