# Generated by Django 3.2.4 on 2024-01-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateprofile',
            name='year',
            field=models.DateField(),
        ),
    ]
