# Generated by Django 3.2.4 on 2024-01-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_certificateprofile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='objective',
            field=models.TextField(max_length=500),
        ),
    ]
