# Generated by Django 3.2.4 on 2024-01-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20240103_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='courseprofile',
            name='college',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='courseprofile',
            name='specialization',
            field=models.CharField(max_length=30),
        ),
    ]
