# Generated by Django 3.2.4 on 2024-01-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20240103_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='award',
            name='source',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='awardprofile',
            name='recognition',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
