# Generated by Django 3.2.4 on 2024-01-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_auto_20240103_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='courseprofile',
            name='college',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='courseprofile',
            name='specialization',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experienceprofile',
            name='company',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
